/*    ==Scripting Parameters==

    Source Server Version : SQL Server 2016 (13.0.4446)
    Source Database Engine Edition : Microsoft SQL Server Enterprise Edition
    Source Database Engine Type : Standalone SQL Server

    Target Server Version : SQL Server 2016
    Target Database Engine Edition : Microsoft SQL Server Enterprise Edition
    Target Database Engine Type : Standalone SQL Server
*/

USE [iss_analysis]
GO

/****** Object:  Table [dw].[instance_perfomance_details]    Script Date: 8/30/2017 1:03:10 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dw].[instance_perfomance_details](
	[instance_id] [int] NULL,
	[time_stamp] [datetime2](7) NULL,
	[connections] [int] NULL,
	[memory_available_mb] [decimal](20, 10) NULL,
	[memory_pages_sec] [decimal](20, 15) NULL,
	[memory_grants_pending] [int] NULL,
	[batch_requests_sec] [decimal](20, 15) NULL,
	[sql_compilations_sec] [decimal](20, 15) NULL,
	[recompilations_sec] [decimal](20, 15) NULL,
	[processor_time_0_pct] [decimal](20, 15) NULL,
	[processor_time_1_pct] [decimal](20, 15) NULL,
	[processor_time_2_pct] [decimal](20, 15) NULL,
	[processor_time_3_pct] [decimal](20, 15) NULL,
	[processor_time_4_pct] [decimal](20, 15) NULL,
	[processor_time_5_pct] [decimal](20, 15) NULL,
	[processor_time_6_pct] [decimal](20, 15) NULL,
	[processor_time_7_pct] [decimal](20, 15) NULL,
	[processor_time_8_pct] [decimal](20, 15) NULL,
	[processor_time_9_pct] [decimal](20, 15) NULL,
	[processor_time_10_pct] [decimal](20, 15) NULL,
	[processor_time_11_pct] [decimal](20, 15) NULL,
	[processor_time_12_pct] [decimal](20, 15) NULL,
	[processor_time_13_pct] [decimal](20, 15) NULL,
	[processor_time_14_pct] [decimal](20, 15) NULL,
	[processor_time_15_pct] [decimal](20, 15) NULL,
	[processor_time_16_pct] [decimal](20, 15) NULL,
	[processor_time_17_pct] [decimal](20, 15) NULL,
	[processor_time_18_pct] [decimal](20, 15) NULL,
	[processor_time_19_pct] [decimal](20, 15) NULL,
	[processor_time_20_pct] [decimal](20, 15) NULL,
	[processor_time_21_pct] [decimal](20, 15) NULL,
	[processor_time_22_pct] [decimal](20, 15) NULL,
	[processor_time_23_pct] [decimal](20, 15) NULL,
	[processor_time_24_pct] [decimal](20, 15) NULL,
	[processor_time_25_pct] [decimal](20, 15) NULL,
	[processor_time_26_pct] [decimal](20, 15) NULL,
	[processor_time_27_pct] [decimal](20, 15) NULL,
	[processor_time_28_pct] [decimal](20, 15) NULL,
	[processor_time_29_pct] [decimal](20, 15) NULL,
	[processor_time_30_pct] [decimal](20, 15) NULL,
	[processor_time_31_pct] [decimal](20, 15) NULL,
	[processor_time_32_pct] [decimal](20, 15) NULL,
	[processor_time_33_pct] [decimal](20, 15) NULL,
	[processor_time_34_pct] [decimal](20, 15) NULL,
	[processor_time_35_pct] [decimal](20, 15) NULL,
	[processor_time_36_pct] [decimal](20, 15) NULL,
	[processor_time_37_pct] [decimal](20, 15) NULL,
	[processor_time_38_pct] [decimal](20, 15) NULL,
	[processor_time_39_pct] [decimal](20, 15) NULL,
	[processor_time_40_pct] [decimal](20, 15) NULL,
	[processor_time_41_pct] [decimal](20, 15) NULL,
	[processor_time_42_pct] [decimal](20, 15) NULL,
	[physical_disk_pct_disk_time_0_pct] [decimal](20, 15) NULL,
	[physical_disk_pct_disk_time_1_pct] [decimal](20, 15) NULL,
	[physical_disk_pct_disk_time_2_pct] [decimal](20, 15) NULL,
	[physical_disk_pct_disk_time_3_pct] [decimal](20, 15) NULL,
	[physical_disk_pct_disk_time_4_pct] [decimal](20, 15) NULL,
	[physical_disk_pct_disk_time_5_pct] [decimal](20, 15) NULL,
	[physical_disk_pct_disk_time_6_pct] [decimal](20, 15) NULL,
	[physical_disk_pct_disk_time_7_pct] [decimal](20, 15) NULL,
	[physical_disk_pct_disk_time_8_pct] [decimal](20, 15) NULL,
	[physical_disk_pct_disk_time_9_pct] [decimal](20, 15) NULL,
	[physical_disk_pct_disk_time_10_pct] [decimal](20, 15) NULL,
	[physical_disk_pct_disk_time_11_pct] [decimal](20, 15) NULL,
	[physical_disk_pct_disk_time_12_pct] [decimal](20, 15) NULL,
	[physical_disk_pct_disk_time_13_pct] [decimal](20, 15) NULL,
	[physical_disk_avg_disk_read_sec_0] [decimal](20, 15) NULL,
	[physical_disk_avg_disk_read_sec_1] [decimal](20, 15) NULL,
	[physical_disk_avg_disk_read_sec_2] [decimal](20, 15) NULL,
	[physical_disk_avg_disk_read_sec_3] [decimal](20, 15) NULL,
	[physical_disk_avg_disk_read_sec_4] [decimal](20, 15) NULL,
	[physical_disk_avg_disk_read_sec_5] [decimal](20, 15) NULL,
	[physical_disk_avg_disk_read_sec_6] [decimal](20, 15) NULL,
	[physical_disk_avg_disk_read_sec_7] [decimal](20, 15) NULL,
	[physical_disk_avg_disk_read_sec_8] [decimal](20, 15) NULL,
	[physical_disk_avg_disk_read_sec_9] [decimal](20, 15) NULL,
	[physical_disk_avg_disk_read_sec_10] [decimal](20, 15) NULL,
	[physical_disk_avg_disk_read_sec_11] [decimal](20, 15) NULL,
	[physical_disk_avg_disk_read_sec_12] [decimal](20, 15) NULL,
	[physical_disk_avg_disk_read_sec_13] [decimal](20, 15) NULL,
	[physical_disk_avg_disk_write_sec_0] [decimal](20, 15) NULL,
	[physical_disk_avg_disk_write_sec_1] [decimal](20, 15) NULL,
	[physical_disk_avg_disk_write_sec_2] [decimal](20, 15) NULL,
	[physical_disk_avg_disk_write_sec_3] [decimal](20, 15) NULL,
	[physical_disk_avg_disk_write_sec_4] [decimal](20, 15) NULL,
	[physical_disk_avg_disk_write_sec_5] [decimal](20, 15) NULL,
	[physical_disk_avg_disk_write_sec_6] [decimal](20, 15) NULL,
	[physical_disk_avg_disk_write_sec_7] [decimal](20, 15) NULL,
	[physical_disk_avg_disk_write_sec_8] [decimal](20, 15) NULL,
	[physical_disk_avg_disk_write_sec_9] [decimal](20, 15) NULL,
	[physical_disk_avg_disk_write_sec_10] [decimal](20, 15) NULL,
	[physical_disk_avg_disk_write_sec_11] [decimal](20, 15) NULL,
	[physical_disk_avg_disk_write_sec_12] [decimal](20, 15) NULL,
	[physical_disk_avg_disk_write_sec_13] [decimal](20, 15) NULL,
	[physical_disk_disk_reads_sec_0] [decimal](20, 15) NULL,
	[physical_disk_disk_reads_sec_1] [decimal](20, 15) NULL,
	[physical_disk_disk_reads_sec_2] [decimal](20, 15) NULL,
	[physical_disk_disk_reads_sec_3] [decimal](20, 15) NULL,
	[physical_disk_disk_reads_sec_4] [decimal](20, 15) NULL,
	[physical_disk_disk_reads_sec_5] [decimal](20, 15) NULL,
	[physical_disk_disk_reads_sec_6] [decimal](20, 15) NULL,
	[physical_disk_disk_reads_sec_7] [decimal](20, 15) NULL,
	[physical_disk_disk_reads_sec_8] [decimal](20, 15) NULL,
	[physical_disk_disk_reads_sec_9] [decimal](20, 15) NULL,
	[physical_disk_disk_reads_sec_10] [decimal](20, 15) NULL,
	[physical_disk_disk_reads_sec_11] [decimal](20, 15) NULL,
	[physical_disk_disk_reads_sec_12] [decimal](20, 15) NULL,
	[physical_disk_disk_reads_sec_13] [decimal](20, 15) NULL,
	[physical_disk_disk_writes_sec_0] [decimal](20, 15) NULL,
	[physical_disk_disk_writes_sec_1] [decimal](20, 15) NULL,
	[physical_disk_disk_writes_sec_2] [decimal](20, 15) NULL,
	[physical_disk_disk_writes_sec_3] [decimal](20, 15) NULL,
	[physical_disk_disk_writes_sec_4] [decimal](20, 15) NULL,
	[physical_disk_disk_writes_sec_5] [decimal](20, 15) NULL,
	[physical_disk_disk_writes_sec_6] [decimal](20, 15) NULL,
	[physical_disk_disk_writes_sec_7] [decimal](20, 15) NULL,
	[physical_disk_disk_writes_sec_8] [decimal](20, 15) NULL,
	[physical_disk_disk_writes_sec_9] [decimal](20, 15) NULL,
	[physical_disk_disk_writes_sec_10] [decimal](20, 15) NULL,
	[physical_disk_disk_writes_sec_11] [decimal](20, 15) NULL,
	[physical_disk_disk_writes_sec_12] [decimal](20, 15) NULL,
	[physical_disk_disk_writes_sec_13] [decimal](20, 15) NULL,
	[processor_queue_length] [int] NULL
) ON [PRIMARY]
GO

