/*    ==Scripting Parameters==

    Source Server Version : SQL Server 2016 (13.0.4446)
    Source Database Engine Edition : Microsoft SQL Server Enterprise Edition
    Source Database Engine Type : Standalone SQL Server

    Target Server Version : SQL Server 2016
    Target Database Engine Edition : Microsoft SQL Server Enterprise Edition
    Target Database Engine Type : Standalone SQL Server
*/

USE [master]
GO

/****** Object:  Database [iss_mondb]    Script Date: 8/29/2017 10:36:36 AM ******/
CREATE DATABASE [iss_mondb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'iss_mondb', FILENAME = N'F:\Data\iss_mondb.mdf' , SIZE = 4202496KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'iss_mondb_log', FILENAME = N'F:\Log\iss_mondb_log.ldf' , SIZE = 5251072KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [iss_mondb] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [iss_mondb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [iss_mondb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [iss_mondb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [iss_mondb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [iss_mondb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [iss_mondb] SET ARITHABORT OFF 
GO

ALTER DATABASE [iss_mondb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [iss_mondb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [iss_mondb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [iss_mondb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [iss_mondb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [iss_mondb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [iss_mondb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [iss_mondb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [iss_mondb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [iss_mondb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [iss_mondb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [iss_mondb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [iss_mondb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [iss_mondb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [iss_mondb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [iss_mondb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [iss_mondb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [iss_mondb] SET RECOVERY FULL 
GO

ALTER DATABASE [iss_mondb] SET  MULTI_USER 
GO

ALTER DATABASE [iss_mondb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [iss_mondb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [iss_mondb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [iss_mondb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [iss_mondb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [iss_mondb] SET QUERY_STORE = OFF
GO

USE [iss_mondb]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [iss_mondb] SET  READ_WRITE 
GO


